import React from 'react';
import { Comment } from '../types';

interface CommentFeedProps {
    comments: Comment[];
    isLoading: boolean;
}

export const CommentFeed: React.FC<CommentFeedProps> = ({ comments, isLoading }) => {
    return (
        <div className="h-full overflow-y-auto custom-scrollbar p-4 space-y-8">
            {comments.length === 0 && !isLoading && (
                <div className="h-full flex flex-col items-center justify-center text-gray-500 space-y-4 opacity-60">
                    <svg className="w-12 h-12" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
                    </svg>
                    <p>No comments yet. Upload a video to start.</p>
                </div>
            )}

            {comments.map((comment) => (
                <div key={comment.id} className="flex gap-4 group animate-in slide-in-from-right-4 fade-in duration-500">
                    {/* Avatar */}
                    <div className="flex-shrink-0">
                        <img
                            src={`https://api.dicebear.com/9.x/avataaars/svg?seed=${comment.persona.avatarSeed}`}
                            alt={comment.persona.handle}
                            className="w-12 h-12 rounded-full bg-gray-800 border border-gray-700 shadow-md"
                        />
                    </div>

                    {/* Content */}
                    <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1">
                            <span className="text-sm font-bold text-gray-100 group-hover:text-brand-400 transition-colors cursor-pointer">
                                {comment.persona.name}
                            </span>
                            <span className="text-xs text-gray-500">@{comment.persona.handle}</span>
                            <span className="text-xs text-gray-600 mx-1">•</span>
                            <span className="text-xs text-gray-500">{comment.timestamp}</span>

                            {/* Source Badge */}
                            {comment.isGenerated && (
                                <div className="group/tooltip relative ml-auto">
                                    <span className="cursor-help text-xs text-brand-400 flex items-center gap-1 bg-brand-900/20 px-1.5 py-0.5 rounded border border-brand-500/20">
                                        <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
                                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                                        </svg>
                                        AI
                                    </span>
                                    <div className="absolute bottom-full right-0 mb-2 w-32 bg-black text-xs text-white p-2 rounded shadow-lg opacity-0 group-hover/tooltip:opacity-100 transition-opacity pointer-events-none border border-gray-800 text-center">
                                        Generated by Gemini 3.0
                                    </div>
                                </div>
                            )}
                        </div>

                        <div className="text-base text-gray-300 leading-relaxed break-words opacity-90 font-light">
                            {comment.text}
                        </div>

                        {/* Actions */}
                        <div className="flex items-center gap-5 mt-3">
                            <button className="flex items-center gap-1.5 text-gray-500 hover:text-white transition-colors group/btn">
                                <svg className="w-4 h-4 group-hover/btn:scale-110 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5" />
                                </svg>
                                <span className="text-xs font-medium">{comment.likes}</span>
                            </button>
                            <button className="text-gray-500 hover:text-white transition-colors">
                                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 14H5.236a2 2 0 01-1.789-2.894l3.5-7A2 2 0 018.736 3h4.018a2 2 0 01.485.06l3.76.94m-7 10v5a2 2 0 002 2h.095c.5 0 .905-.405.905-.905 0-.714.211-1.412.608-2.006L17 13V4m-7 10h2" />
                                </svg>
                            </button>
                            <button className="text-gray-500 hover:text-brand-400 transition-colors text-xs font-medium">
                                Reply
                            </button>
                        </div>
                    </div>

                    {/* Persona Badge */}
                    <div className="opacity-0 group-hover:opacity-100 transition-opacity absolute right-4 top-2 pointer-events-none">
                        <span className="text-[10px] uppercase tracking-wider font-bold text-gray-500 border border-gray-800 rounded px-1.5 py-0.5 bg-gray-950/80 backdrop-blur-sm">
                            {comment.persona.trait}
                        </span>
                    </div>
                </div>
            ))}

            {isLoading && (
                <div className="flex gap-4 animate-pulse">
                    <div className="w-12 h-12 rounded-full bg-gray-800/50"></div>
                    <div className="flex-1 space-y-3 py-1">
                        <div className="h-4 bg-gray-800/50 rounded w-1/4"></div>
                        <div className="h-16 bg-gray-800/50 rounded w-full"></div>
                    </div>
                </div>
            )}
        </div>
    );
};
